### ISSUE TITLE
Create snapshot directory if it does not exist?

### ISSUE THREAD

**Issue by dentarg** [tomazzlender/snapshot_ui#1]
Same as https://github.com/tomazzlender/snapshot_inspector/issues/2

**Comment by tomazzlender** [comment]
This will be resolved in the next release. It's addressed in this commit https://github.com/tomazzlender/snapshot_ui/commit/d2621c7a67342ded4a76905ccb66d9df86b1af0a.

Instead of creating a directory, a new command is introduced `snapshot_ui live path/to/config/snapshot_ui.rb` that loads the configuration file for the library, which in turn contains the directory path.

**Comment by tomazzlender** [comment]
Resolved here https://github.com/tomazzlender/snapshot_ui/commit/d2621c7a67342ded4a76905ccb66d9df86b1af0a and part of `0.4.0` release.

Instead of doing

```
bundle exec snapshot watch tmp/snapshot_ui
```

A user should use

```
bundle exec snapshot live config/snapshot_ui.rb
```

Where `config/snapshot_ui.rb` is a place where Snapshot UI is configured.

(example `config/snapshot_ui.rb`)
```
require "snapshot_ui"

SnapshotUI.configure do |config|
  config.storage_directory = File.expand_path("../tmp/snapshot_ui", __dir__)
  config.project_root_directory = File.expand_path("../", __dir__),
  web_url: "http://localhost:3000/ui/snapshots"
end
```
